//! DNS application for the native F5 tunnel.
//!
//! After the tunnel is up, the negotiated DNS servers and search domains must be
//! applied to the host resolver so split-tunnel name resolution works. The
//! mechanism differs by distro; modern **Fedora and Ubuntu** both use
//! `systemd-resolved` (`resolvectl`), with `resolvconf` and a direct
//! `/etc/resolv.conf` rewrite as fallbacks.
//!
//! Following the test-actors methodology, the mechanism is chosen by a pure,
//! testable [`detect_backend`] and applied behind a [`DnsApplier`] seam. The
//! command construction is pure ([`resolvectl_args`]) and unit-tested; only the
//! final process spawn touches the OS.

use crate::vpn::transport::TunConfig;

/// Which host DNS mechanism to drive.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DnsBackend {
    /// `systemd-resolved` via `resolvectl` (Fedora, Ubuntu, most modern distros).
    SystemdResolved,
    /// `resolvconf` helper.
    Resolvconf,
    /// Direct `/etc/resolv.conf` rewrite (last resort).
    ResolvConfFile,
    /// No DNS to apply / nothing detected.
    None,
}

/// Detect the DNS backend from observed system facts.
///
/// Pure and testable: callers pass whether `systemd-resolved` is active and
/// whether `resolvconf` exists, so the decision logic can be exercised without
/// touching the OS.
pub fn detect_backend(systemd_resolved_active: bool, resolvconf_present: bool) -> DnsBackend {
    if systemd_resolved_active {
        DnsBackend::SystemdResolved
    } else if resolvconf_present {
        DnsBackend::Resolvconf
    } else {
        DnsBackend::ResolvConfFile
    }
}

/// Build the `resolvectl dns <iface> <servers...>` argument vector.
pub fn resolvectl_dns_args(iface: &str, servers: &[String]) -> Vec<String> {
    let mut args = vec!["dns".to_string(), iface.to_string()];
    args.extend(servers.iter().cloned());
    args
}

/// Build the `resolvectl domain <iface> <domains...>` argument vector.
///
/// Search domains are passed as-is; a routing-only domain would be prefixed with
/// `~`, but for split-DNS we register them as search domains.
pub fn resolvectl_domain_args(iface: &str, domains: &[String]) -> Vec<String> {
    let mut args = vec!["domain".to_string(), iface.to_string()];
    args.extend(domains.iter().cloned());
    args
}

/// Render the contents of a `/etc/resolv.conf` for the given config.
pub fn resolv_conf_contents(config: &TunConfig) -> String {
    let mut out = String::from("# Generated by akon native F5 backend\n");
    if !config.domains.is_empty() {
        out.push_str(&format!("search {}\n", config.domains.join(" ")));
    }
    for dns in &config.dns {
        out.push_str(&format!("nameserver {dns}\n"));
    }
    out
}

/// Seam for applying DNS settings to the host.
///
/// The production impl drives the detected mechanism; the test impl records what
/// would be applied, so the orchestration is validated without modifying the
/// host resolver.
pub trait DnsApplier: Send {
    /// Apply the negotiated DNS servers/domains for interface `iface`.
    fn apply(&mut self, iface: &str, config: &TunConfig) -> std::io::Result<()>;

    /// Revert any DNS changes for `iface` (best-effort).
    fn revert(&mut self, iface: &str) -> std::io::Result<()>;

    /// Whether this applier actually mutates the **host** resolver (and thus
    /// must be reverted on teardown). The real `SystemDnsApplier` returns `true`;
    /// `NoopDns` and test fakes return `false`. The orchestrator uses this to
    /// decide whether to record a DNS revert in the teardown plan — so a test or
    /// container run never schedules a `resolvectl` call against the host
    /// resolver (which is NOT namespaced and would prompt polkit / disturb the
    /// host).
    fn mutates_host(&self) -> bool {
        true
    }
}

/// A no-op DNS applier (used when no DNS was negotiated or DNS handling is
/// delegated to the operator).
#[derive(Default)]
pub struct NoopDns;

impl DnsApplier for NoopDns {
    fn apply(&mut self, _iface: &str, _config: &TunConfig) -> std::io::Result<()> {
        Ok(())
    }
    fn revert(&mut self, _iface: &str) -> std::io::Result<()> {
        Ok(())
    }
    fn mutates_host(&self) -> bool {
        false
    }
}

/// Production DNS applier that detects the distro mechanism and drives it.
#[cfg(target_os = "linux")]
pub struct SystemDnsApplier {
    backend: DnsBackend,
}

#[cfg(target_os = "linux")]
impl SystemDnsApplier {
    /// Detect the host DNS backend and build an applier for it.
    pub fn detect() -> Self {
        use std::path::Path;
        use std::process::Command;

        let systemd_resolved_active = Command::new("systemctl")
            .args(["is-active", "--quiet", "systemd-resolved"])
            .status()
            .map(|s| s.success())
            .unwrap_or(false);
        let resolvconf_present = Path::new("/sbin/resolvconf").exists()
            || Path::new("/usr/sbin/resolvconf").exists()
            || Path::new("/usr/bin/resolvconf").exists();

        Self {
            backend: detect_backend(systemd_resolved_active, resolvconf_present),
        }
    }

    /// The detected backend (for diagnostics/logging).
    pub fn backend(&self) -> DnsBackend {
        self.backend
    }
}

#[cfg(target_os = "linux")]
impl DnsApplier for SystemDnsApplier {
    fn apply(&mut self, iface: &str, config: &TunConfig) -> std::io::Result<()> {
        use std::process::Command;

        if config.dns.is_empty() {
            return Ok(());
        }

        let debug = std::env::var("AKON_F5_DEBUG").as_deref() == Ok("1");
        match self.backend {
            DnsBackend::SystemdResolved => {
                // 1) Point the tun link's DNS at the VPN servers.
                let dns_args = resolvectl_dns_args(iface, &config.dns);
                if debug {
                    eprintln!("[dns] resolvectl {}", dns_args.join(" "));
                }
                let out = Command::new("resolvectl").args(&dns_args).output()?;
                if !out.status.success() {
                    let msg = String::from_utf8_lossy(&out.stderr);
                    if debug {
                        eprintln!("[dns] resolvectl dns FAILED: {}", msg.trim());
                    }
                    return Err(std::io::Error::new(
                        std::io::ErrorKind::Other,
                        format!("resolvectl dns failed: {}", msg.trim()),
                    ));
                }

                // 2) Routing domains. For a full tunnel we make the VPN DNS the
                //    default for ALL lookups via the catch-all routing domain
                //    `~.`, plus the search domains. Without a routing domain,
                //    systemd-resolved would NOT send queries to this link.
                let mut domains = vec!["~.".to_string()];
                domains.extend(config.domains.iter().cloned());
                let dom_args = resolvectl_domain_args(iface, &domains);
                if debug {
                    eprintln!("[dns] resolvectl {}", dom_args.join(" "));
                }
                let dout = Command::new("resolvectl").args(&dom_args).output()?;
                if debug && !dout.status.success() {
                    eprintln!(
                        "[dns] resolvectl domain WARN: {}",
                        String::from_utf8_lossy(&dout.stderr).trim()
                    );
                }

                // 3) Mark this link as eligible for the DNS default route, so
                //    systemd-resolved actually prefers it for unmatched queries
                //    (otherwise the Global/other-link DNS can still win).
                let dr = Command::new("resolvectl")
                    .args(["default-route", iface, "yes"])
                    .output();
                if debug {
                    match &dr {
                        Ok(o) if o.status.success() => {
                            eprintln!("[dns] resolvectl default-route {iface} yes")
                        }
                        Ok(o) => eprintln!(
                            "[dns] resolvectl default-route WARN: {}",
                            String::from_utf8_lossy(&o.stderr).trim()
                        ),
                        Err(e) => eprintln!("[dns] resolvectl default-route error: {e}"),
                    }
                }

                // 4) Flush caches so stale (pre-VPN) answers don't linger.
                let _ = Command::new("resolvectl").arg("flush-caches").status();

                // 5) Self-verify: show the link's resolved view + the current
                //    global resolution decision, so a misroute is visible.
                if debug {
                    if let Ok(o) = Command::new("resolvectl").args(["status", iface]).output() {
                        eprintln!(
                            "[dns] resolvectl status {iface}:\n{}",
                            String::from_utf8_lossy(&o.stdout)
                        );
                    }
                    eprintln!("[dns] systemd-resolved configured on {iface}; VPN DNS default-route enabled");
                }
                Ok(())
            }
            DnsBackend::Resolvconf => {
                // Feed resolv.conf content to `resolvconf -a <iface>`.
                use std::io::Write;
                use std::process::Stdio;
                let mut child = Command::new("resolvconf")
                    .args(["-a", iface])
                    .stdin(Stdio::piped())
                    .spawn()?;
                if let Some(stdin) = child.stdin.as_mut() {
                    stdin.write_all(resolv_conf_contents(config).as_bytes())?;
                }
                child.wait()?;
                Ok(())
            }
            DnsBackend::ResolvConfFile => {
                std::fs::write("/etc/resolv.conf", resolv_conf_contents(config))
            }
            DnsBackend::None => Ok(()),
        }
    }

    fn revert(&mut self, iface: &str) -> std::io::Result<()> {
        use std::process::Command;
        match self.backend {
            DnsBackend::SystemdResolved => {
                // resolved reverts automatically when the link goes down; best-effort.
                let _ = Command::new("resolvectl").args(["revert", iface]).status();
                Ok(())
            }
            DnsBackend::Resolvconf => {
                let _ = Command::new("resolvconf").args(["-d", iface]).status();
                Ok(())
            }
            // For a direct file rewrite we cannot reliably restore; leave as-is.
            DnsBackend::ResolvConfFile | DnsBackend::None => Ok(()),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detect_prefers_systemd_resolved() {
        // Both Fedora and Ubuntu: systemd-resolved active.
        assert_eq!(detect_backend(true, true), DnsBackend::SystemdResolved);
        assert_eq!(detect_backend(true, false), DnsBackend::SystemdResolved);
    }

    #[test]
    fn detect_falls_back_to_resolvconf_then_file() {
        assert_eq!(detect_backend(false, true), DnsBackend::Resolvconf);
        assert_eq!(detect_backend(false, false), DnsBackend::ResolvConfFile);
    }

    #[test]
    fn resolvectl_args_built_correctly() {
        let servers = vec!["10.0.0.53".to_string(), "10.0.0.54".to_string()];
        assert_eq!(
            resolvectl_dns_args("tun0", &servers),
            vec!["dns", "tun0", "10.0.0.53", "10.0.0.54"]
        );
        let domains = vec!["corp.example.com".to_string()];
        assert_eq!(
            resolvectl_domain_args("tun0", &domains),
            vec!["domain", "tun0", "corp.example.com"]
        );
    }

    #[test]
    fn resolv_conf_contents_renders_search_and_nameservers() {
        let cfg = TunConfig {
            dns: vec!["10.0.0.53".into(), "10.0.0.54".into()],
            domains: vec!["corp.example.com".into()],
            ..Default::default()
        };
        let text = resolv_conf_contents(&cfg);
        assert!(text.contains("search corp.example.com\n"));
        assert!(text.contains("nameserver 10.0.0.53\n"));
        assert!(text.contains("nameserver 10.0.0.54\n"));
    }

    #[test]
    fn noop_applier_is_ok() {
        let mut dns = NoopDns;
        let cfg = TunConfig::default();
        assert!(dns.apply("tun0", &cfg).is_ok());
        assert!(dns.revert("tun0").is_ok());
    }
}
